name: NodeJS

on:
  push:
    branches:
    - '**'
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build ./NodeJS/Unit-01
      working-directory: ./NodeJS/Unit-01
      run: |
        npm install
        npm test
    
    - name: Build ./NodeJS/Unit-02
      working-directory: ./NodeJS/Unit-02
      run: |
        npm install
        npm test
